imports:
    - php

filter:
    paths: ["app/Models/*", "routes/web.php"]
    excluded_paths: [vendor/*, build/*, app/Models/User.php, "app/Http/Controllers/*"]

build:
    project_setup:
        override:
            - true
    nodes:
        my-tests:
            environment:
                php:
                    version: 8.1.2
    tests:
        override:
            -
                command: "make phpunit"
                coverage:
                    file: "build/coverage.clover"
                    format: "php-clover"